id: P003303
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 10:53:50.699723
source_metadata:
  id: bdr:W27609
  title: མ་ཎི་འཁོར་ལོའི་ཕན་ཡོན
  author: ''
  volumes:
    5fcc3290bf5e4ec1a0406fedab09ff4d:
      image_group_id: I4501
      title: ''
      volume_number: 1
      total_pages: 32
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
